services:
  - type: web
    name: webly-ia
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        fromDatabase:
          name: supabase
          property: url
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        fromDatabase:
          name: supabase
          property: anonKey
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromDatabase:
          name: supabase
          property: serviceRoleKey
      - key: OPENAI_API_KEY
        fromDatabase:
          name: openai
          property: apiKey
